return {
  require('plugins.colorscheme'),
  require('plugins.lualine'),
  require('plugins.barbecue'),
  require('plugins.treesitter'),
  require('plugins.lsp'),
  require('plugins.completions'),
  require('plugins.snippets'),
  require('plugins.coq'),

  require('plugins.telescope'),
  require('plugins.git'),
  require('plugins.oil'),
  require('plugins.tmux'),
  require('plugins.cursor'),
  require('plugins.harpoon'),
  require('plugins.undotree'),
  require('plugins.whichkey'),
  require('plugins.debugging'),
  require('plugins.autoformat'),
}
